# Generated by Django 6.0.4 on 2026-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Title (FR)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Title (AR)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description_fr', models.TextField(verbose_name='Short Description (FR)')),
                ('short_description_ar', models.TextField(blank=True, verbose_name='Short Description (AR)')),
                ('full_description_fr', models.TextField(verbose_name='Full Description (FR)')),
                ('full_description_ar', models.TextField(blank=True, verbose_name='Full Description (AR)')),
                ('benefits_fr', models.JSONField(default=list, verbose_name='Benefits (FR)')),
                ('benefits_ar', models.JSONField(default=list, verbose_name='Benefits (AR)')),
                ('featured_image', models.ImageField(upload_to='services/', verbose_name='Featured Image')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube Video URL')),
                ('meta_title_fr', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (FR)')),
                ('meta_title_ar', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (AR)')),
                ('meta_description_fr', models.TextField(blank=True, verbose_name='Meta Description (FR)')),
                ('meta_description_ar', models.TextField(blank=True, verbose_name='Meta Description (AR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
