# Generated by Django 6.0.4 on 2026-05-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Featured Image'),
        ),
    ]
