# Generated by Django 6.0.4 on 2026-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DigiCode Web Agency', max_length=100, verbose_name='Site Name')),
                ('site_description_fr', models.TextField(blank=True, verbose_name='Site Description (FR)')),
                ('site_description_ar', models.TextField(blank=True, verbose_name='Site Description (AR)')),
                ('whatsapp_number', models.CharField(default='+212600000000', max_length=20, verbose_name='WhatsApp Number')),
                ('email', models.EmailField(default='contact@digicode.ma', max_length=254, verbose_name='Email')),
                ('address_fr', models.TextField(blank=True, verbose_name='Address (FR)')),
                ('address_ar', models.TextField(blank=True, verbose_name='Address (AR)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
