# Generated by Django 6.0.4 on 2026-04-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_google_analytics_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#2563EB', help_text='Blue color', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ar',
            field=models.TextField(blank=True, help_text='Copyright text or tagline for footer (Arabic)', verbose_name='Footer Text (AR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_fr',
            field=models.TextField(blank=True, help_text='Copyright text or tagline for footer', verbose_name='Footer Text (FR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='highlight_color',
            field=models.CharField(default='#F59E0B', help_text='Amber/gold color', max_length=7, verbose_name='Highlight Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#0F172A', help_text='Dark slate color', max_length=7, verbose_name='Primary Color'),
        ),
    ]
