# Generated by Django 6.0.4 on 2026-05-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('short_description', models.TextField(help_text='Brief summary shown on the list page', max_length=500, verbose_name='Short Description')),
                ('full_description', models.TextField(help_text='Detailed description shown on the detail page', verbose_name='Full Description')),
                ('link', models.URLField(blank=True, help_text='External link to the live project', null=True, verbose_name='Project Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
