# Generated by Django 6.0.4 on 2026-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project thumbnail or screenshot', null=True, upload_to='projects/', verbose_name='Image'),
        ),
    ]
