# Generated by Django 6.0.4 on 2026-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Full Description (AR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_fr',
            field=models.TextField(default='', help_text='Detailed description shown on the detail page', verbose_name='Full Description (FR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_ar',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Short Description (AR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_fr',
            field=models.TextField(default='', help_text='Brief summary shown on the list page', max_length=500, verbose_name='Short Description (FR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (AR)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(default='', max_length=200, verbose_name='Title (FR)'),
        ),
    ]
